### ISSUE TITLE
Mistake in stm8_interrupt_vector.h

### ISSUE THREAD

**Issue by blkhawk** [gicking/STM8_templates#4]
In line 320: #define __TIM6:UPD_VECTOR__     23
I think the ":" should be a "_". I found this while trying to get TIM4 to work - sadly without much success yet. I think the interrupt mapping might be completely different. Also i am getting a compiler error on the ISR_HANDLEr about it being "old style".

**Comment by gicking** [comment]
Hello blkhawk,

Ad 1) you are correct that was a typo, and I already fixed it.

Ad 2) as already mentioned in the CLK_PCKENR issue, so far my templates have only been tested with STM8S and STM8A, not the newer STM8L. Unfortunately a day has only 24hrs, and my vacation is also over, so I am afraid consolidating across the different families will take some time. Sorry!   :-(

Ad 3) which compiler and version are you using? Because I don’t see any "old style error message (SDCC xxx)

PS: did you already succeed in getting TIM4 to run, e.g. by adapting the CLK_PCKENR* registers? Please drop me a note. Thanks in advance!

**Comment by blkhawk** [comment]
2) well I am doing some very hackish changes to make it work. Its simply that your code worked for me right away at least up to a point so I stuck with it. 
3) Cosmic because that is the first that I found in the selection list of STVisualD  that was unrestricted for STM8. 

Add: nope - i did neither get the Millis() with TIM4 to work nor did I get its delay to trigger. Same goes for me trying to get ADC1 to run.

**Comment by blkhawk** [comment]
Say do you hang in any IRC channels so we can talk?

**Comment by gicking** [comment]
sorry, no. Is that difficult to set up (under Linux)?

**Comment by blkhawk** [comment]
uh - its a very old timey way of communicating - think slack only in 1986 ;) 
you can use a web client - I just joined #sdcc on freenode asking about how to get rid of cosmic.

**Comment by gicking** [comment]
that was easy :-)
